src/menus/urls.py
from django.conf.urls import url

from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView
)

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='edit'),
    url(r'^$', ItemListView.as_view(), name ='list')
]

src/training/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView, LogoutView

from menus.views import HomeView
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view, ProfileSearchDetailview

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^search/$', ProfileSearchDetailview.as_view(), name='search'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^u/', include('profiles.urls', namespace='profiles')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/menus/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse

from restaurants.models import RestaurantLocation

class Item(models.Model):
    user        = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant  = models.ForeignKey(RestaurantLocation)
    name        = models.CharField(max_length=120)
    contents    = models.TextField(help_text = 'Separate each item by comma')
    excludes    = models.TextField(blank=True, null=True, help_text = 'Separate each item by comma')
    public      = models.BooleanField(default=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-updated', '-timestamp']

    def get_contents(self):
        return self.contents.split(",")

    def get_excludes(self):
        return self.excludes.split(",")

# Create your models here.

src/menus/forms.py
from django import forms

from .models import Item
from restaurants.models import RestaurantLocation

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'restaurant',
            'name',
            'contents',
            'excludes',
            'public'
        ]
    
    def __init__(self, user=None, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user)

    

src/menus/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View

from .forms import ItemForm
from .models import Item

class HomeView(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return redirect('/login')
            # return render(request, "registration/login.html", {})
        
        user = request.user
        is_following_user_ids = [x.user.id for x in user.is_following.all()]
        qs = Item.objects.filter(user__id__in=is_following_user_ids, public=True)
        print(qs)
        return render(request, "home.html", {'object_list': qs})

class ItemListView(ListView, LoginRequiredMixin):
    login_url = '/login/'
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

class ItemDetailView(DetailView, LoginRequiredMixin):
    login_url = '/login/'
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

class ItemCreateView(CreateView, LoginRequiredMixin):
    form_class = ItemForm
    login_url = '/login/'
    template_name = 'form.html'
    
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        return super(ItemCreateView, self).form_valid(form)
    
    def get_form_kwargs(self):
        kwargs = super(ItemCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(ItemCreateView, self).get_context_data(**kwargs)
        context['title'] = "Add Item"
        context['return_url'] = reverse('menus:list')
        return context     

class ItemUpdateView(UpdateView, LoginRequiredMixin):
    form_class = ItemForm
    login_url = '/login/'
    template_name = 'menus/detail-update.html'
    
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        return super(ItemUpdateView, self).form_valid(form)
        
    def get_form_kwargs(self):
        kwargs = super(ItemUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(ItemUpdateView, self).get_context_data(**kwargs)
        context['title'] = "Make Changes:"
        context['return_url'] = reverse('menus:list')
        return context           
# Create your views here.

src/menus/templates/menus/detail-update.html
{% extends "base.html" %}

{% block head_title %}
    Menu Items ||
    {{ block.super }}
{% endblock head_title %}

{% block content %}

<section id="callaction" class="home-section paddingtop-90 paddingbot-10">	
        <div class="container">
             <div class="row">
                 <div class="col-md-12">
                     <div class="callaction bg-gray">
                         <div class="row">
                            <h6>{{ form.instance.name }} Details</h6>
                            <p>Location: {{ form.instance.restaurant }}</p>
                            {% if form.instance.contents %}
                                <p>Contents: </p>
                                <ul>
                                    {% for content in form.instance.get_contents %}
                                        <li>
                                            {{ content }}
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            {% if form.instance.excludes %}
                                <p>Excludes: </p>
                                <ul>
                                    {% for exclude in form.instance.get_excludes %}
                                        <li>
                                            {{ exclude }}
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                     </div>
                 </div>
             </div>
             {% include 'snippets/form-snippet.html' with form=form %}
         </div>
 </section>	
 {% endblock content %}

src/menus/templates/menus/item_detail.html
{% extends "base.html" %}

{% block head_title %}
    Menu Items ||
    {{ block.super }}
{% endblock head_title %}

{% block content %}

<section id="callaction" class="home-section paddingtop-90 paddingbot-10">	
        <div class="container">
             <div class="row">
                 <div class="col-md-12">
                     <div class="callaction bg-gray">
                         <div class="row">
                            <h6>{{ object.name }} Details</h6>
                            <p>Location: {{ object.restaurant }}</p>
                            {% if object.contents %}
                                <p>Contents: </p>
                                <ul>
                                    {% for content in object.get_contents %}
                                        <li>
                                            {{ content }}
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            {% if object.excludes %}
                                <p>Excludes: </p>
                                <ul>
                                    {% for exclude in object.get_excludes %}
                                        <li>
                                            {{ exclude }}
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                     </div>
                 </div>
             </div>
         </div>
 </section>	
 {% endblock content %}

src/menus/templates/menus/item_list.html
{% extends "base.html" %}

{% block head_title %}
    Menu Items ||
    {{ block.super }}
{% endblock head_title %}

{% block content %}

<section id="callaction" class="home-section paddingtop-90 paddingbot-10">	
        <div class="container">
             <div class="row">
                 <div class="col-md-12">
                     <div class="callaction bg-gray">
                         <div class="row">
                            <h1>Menu Items List</h1>
                            <h5><a   class="btn btn-success" href="{% url 'menus:create' %}">Add Item</a></h5>
                         </div>
                         <div class="row">
                            <ul>
                                {% for object in object_list %}
                                    <li>
                                        <h6>
                                            <a href ="{{ object.get_absolute_url }}">
                                                {{ object.name }}
                                            </a>
                                        </h6>
                                    </li>
                                    {% if object.contents %}
                                        <p>Contents: </p>
                                        <ul>
                                            {% for content in object.get_contents %}
                                                <li>
                                                    {{ content }}
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                    {% if object.excludes %}
                                        <p>Excludes: </p>
                                        <ul>
                                            {% for exclude in object.get_excludes %}
                                                <li>
                                                    {{ exclude }}
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                {% empty %}
                                    <li><a  class="btn btn-success" href="{% url 'menus:create' %}">Add One Item</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                     </div>
                 </div>
             </div>
         </div>
 </section>	
 {% endblock content %}