src/menus/urls.py
from django.conf.urls import url

from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView
)

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='edit'),
    url(r'^$', ItemListView.as_view(), name ='list')
]

src/restaurants/urls.py
from django.conf.urls import url

from .views import (
    RestaurantListView, 
    RestaurantDetailView,
    RestaurantCreateView,
    RestaurantUpdateView
)

urlpatterns = [
    url(r'^$', RestaurantListView.as_view(), name ='list'),
    url(r'^create/$', RestaurantCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', RestaurantUpdateView.as_view(), name='detail'),
    #url(r'^(?P<slug>[\w-]+)/edit$', RestaurantUpdateView.as_view(), name='edit'),
]

src/training/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView, LogoutView

from menus.views import HomeView
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view, ProfileSearchDetailview

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^search/$', ProfileSearchDetailview.as_view(), name='search'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^u/', include('profiles.urls', namespace='profiles')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/restaurants/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save

from .utils import unique_slug_generator

User = settings.AUTH_USER_MODEL

class RestaurantLocationQuerySet(models.query.QuerySet):
    def search(self, query):
        if query:
            query.strip()
            return self.filter(
                Q(name__icontains=query)|
                Q(location__icontains=query)|
                Q(category__icontains=query)|
                Q(item__name__icontains=query)|
                Q(item__contents__icontains=query)
                ).distinct()
        return self
    # RestaurantLocation.objects.all().search(query)

class RestaurantLocationManager(models.Manager):
    def get_queryset(self):
        return RestaurantLocationQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().filter(name__icontains=query)
    # RestaurantLocation.objects.search()

class RestaurantLocation(models.Model):
    owner       = models.ForeignKey(User)
    name        = models.CharField(max_length=120)
    location    = models.CharField(max_length=120, null=True, blank=True)
    category    = models.CharField(max_length=120, null=True, blank=False)
    timestamp   = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)
    slug        = models.SlugField(null=True, blank=True)

    objects = RestaurantLocationManager()
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('restaurants:detail', kwargs={'slug': self.slug})

    @property
    def title(self):
        return self.name

def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(rl_pre_save_receiver, sender=RestaurantLocation)

src/restaurants/forms.py
from django import forms

from .models import RestaurantLocation
from .validators import validate_category

class RestaurantLocationCreateForm (forms.ModelForm):
    category = forms.CharField(required=False, validators=[validate_category])
    class Meta:
        model = RestaurantLocation
        fields = [
            'name',
            'location',
            'category',
            'slug'
        ]
        

src/restaurants/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView

from .forms import RestaurantLocationCreateForm
from .models import RestaurantLocation

class RestaurantListView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)


class RestaurantDetailView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

class RestaurantCreateView(LoginRequiredMixin, CreateView):
    form_class = RestaurantLocationCreateForm
    login_url = '/login/'
    template_name = 'form.html'
    # success_url = '/restaurants'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(RestaurantCreateView, self).form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super(RestaurantCreateView, self).get_context_data(**kwargs)
        context['title'] = "Add Restaurant"
        context['return_url'] = reverse('restaurants:list')
        return context

class RestaurantUpdateView(LoginRequiredMixin, UpdateView):
    form_class = RestaurantLocationCreateForm
    login_url = '/login/'
    template_name = 'restaurants/detail-update.html'
    # success_url = '/restaurants'

    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(UpdateView, self).form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super(UpdateView, self).get_context_data(**kwargs)
        context['title'] = "Make Changes:"
        context['return_url'] = reverse('restaurants:list')
        return context

src/restaurants/templates/restaurants/detail-update.html
{% extends "base.html" %}

{% block head_title %}
    {{ form.instance.title }} ||
    {{ block.super }}
{% endblock head_title %}

{% block content %}

<section id="callaction" class="home-section paddingtop-90 paddingbot-10">	
        <div class="container">
             <div class="row">
                 <div class="col-md-12">
                     <div class="callaction bg-gray">
                         <div class="row">
                            <h5>Name: {{ form.instance.name }}<small> <br/>Category: {{ form.instance.category }}</small></h1>
                         </div>
                         <div class="row">
                            <h6>Location: {{ form.instance.location }}</h2>
                        </div>
                        <div class="row">
                            <h6>Added on: {{ form.instance.timestamp }}</h2>
                        </div>
                        <div class="row">
                            <h6>Updated: {{ form.instance.updated|timesince }}</h2>
                        </div>    
                     </div>
                 </div>
             </div>
             {% include 'snippets/form-snippet.html' with form=form %}
         </div>
 </section>	
{% endblock content %}

src/restaurants/templates/restaurants/restaurantlocation_detail.html
{% extends "base.html" %}

{% block head_title %}
    Restaurant Detail ||
    {{ block.super }}
{% endblock head_title %}

{% block content %}

<section id="callaction" class="home-section paddingtop-90 paddingbot-10">	
        <div class="container">
             <div class="row">
                 <div class="col-md-12">
                     <div class="callaction bg-gray">
                         <div class="row">
                            <h5>Name: {{ object.name }}<small> <br/>Category: {{ object.category }}</small></h1>
                         </div>
                         <div class="row">
                            <h6>Location: {{ object.location }}</h2>
                        </div>
                        <div class="row">
                            <h6>Added on: {{ object.timestamp }}</h2>
                        </div>
                        <div class="row">
                            <h6>Updated: {{ object.updated|timesince }}</h2>
                        </div>    
                     </div>
                 </div>
             </div>
         </div>
 </section>	
{% endblock content %}

src/restaurants/templates/restaurants/restaurantlocation_list.html
{% extends "base.html" %}

{% block head_title %}
    Restaurants ||
    {{ block.super }}
{% endblock head_title %}

{% block content %}

<section id="callaction" class="home-section paddingtop-90 paddingbot-10">	
        <div class="container">
             <div class="row">
                 <div class="col-md-12">
                     <div class="callaction bg-gray">
                         <div class="row">
                            <h1>My Restaurants <br/><small><a  class="btn btn-success" href="{% url 'restaurants:create' %}">Add Restaurant</a></small></h1>
                         </div>
                         <div class="row">
                             <ul>
                                {% for object in object_list %}
                                    <li><a href="{{ object.get_absolute_url }}">{{ object.name }}</a></li>
                                {% empty %}
                                    <li><a  class="btn btn-success" href="{% url 'restaurants:create' %}">Add One Restaurant</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                     </div>
                 </div>
             </div>
         </div>
 </section>	

{% endblock content %}

src/restaurants/templates/restaurants/restaurants_list.html
{% extends "base.html" %}

{% block head_title %}
    Restaurants ||
    {{ block.super }}
{% endblock head_title %}

{% block content %}
<h1>Restaurant List</h1>
<ul>
    {% for object in object_list %}
        <li>{{ object.name }}</li>
    {% endfor %}
</ul>
{% endblock content %}