src/menus/urls.py
from django.conf.urls import url

from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView
)

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='edit'),
    url(r'^$', ItemListView.as_view(), name ='list')
]

src/training/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView, LogoutView

from menus.views import HomeView
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view, ProfileSearchDetailview

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^search/$', ProfileSearchDetailview.as_view(), name='search'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^u/', include('profiles.urls', namespace='profiles')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/templates/snippets/css.html
{% load staticfiles %}
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" type="text/css">
<link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{% static "plugins/cubeportfolio/css/cubeportfolio.min.css" %}">
<link href="{% static "css/nivo-lightbox.css" %}" rel="stylesheet" />
<link href="{% static "css/nivo-lightbox-theme/default/default.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "css/owl.carousel.css" %}" rel="stylesheet" media="screen" />
<link href="{% static "css/owl.theme.css" %}" rel="stylesheet" media="screen" />
<link href="{% static "css/animate.css" %}" rel="stylesheet" />
<link href="{% static "css/style.css" %}" rel="stylesheet">

<!-- boxed bg -->
<link id="bodybg" href="{% static "bodybg/bg1.css" %}" rel="stylesheet" type="text/css" />
<!-- template skin -->
<link id="t-colors" href="{% static "color/default.css" %}" rel="stylesheet">

src/templates/snippets/footer.html
<footer>
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-md-4">
					<div class="wow fadeInDown" data-wow-delay="0.1s">
					<div class="widget">
						<h5>About Asa Ta Eat</h5>
						<p>
						Lorem ipsum dolor sit amet, ne nam purto nihil impetus, an facilisi accommodare sea
						</p>
					</div>
					</div>
					<div class="wow fadeInDown" data-wow-delay="0.1s">
					<div class="widget">
						<h5>Information</h5>
						<ul>
							<li><a href="#">Home</a></li>
						</ul>
					</div>
					</div>
				</div>
				<div class="col-sm-6 col-md-4">
					<div class="wow fadeInDown" data-wow-delay="0.1s">
					<div class="widget">
						<h5>Asa Ta Eat</h5>
						<p>
						Nam leo lorem, tincidunt id risus ut, ornare tincidunt naqunc sit amet.
						</p>
						<ul>
							<li>
								<span class="fa-stack fa-lg">
									<i class="fa fa-circle fa-stack-2x"></i>
									<i class="fa fa-calendar-o fa-stack-1x fa-inverse"></i>
								</span> Monday - Saturday, 8am to 10pm
							</li>
							<li>
								<span class="fa-stack fa-lg">
									<i class="fa fa-circle fa-stack-2x"></i>
									<i class="fa fa-phone fa-stack-1x fa-inverse"></i>
								</span> +62 0888 904 711
							</li>
							<li>
								<span class="fa-stack fa-lg">
									<i class="fa fa-circle fa-stack-2x"></i>
									<i class="fa fa-envelope-o fa-stack-1x fa-inverse"></i>
								</span> hello@asataeat.com
							</li>

						</ul>
					</div>
					</div>
				</div>
				<div class="col-sm-6 col-md-4">
					<div class="wow fadeInDown" data-wow-delay="0.1s">
					<div class="widget">
						<h5>Our location</h5>
						<p>The Suithouse V303, Kuningan City, Jakarta Indonesia 12940</p>		
						
					</div>
					</div>
					<div class="wow fadeInDown" data-wow-delay="0.1s">
					<div class="widget">
						<h5>Follow us</h5>
						<ul class="company-social">
								<li class="social-facebook"><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li class="social-twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li class="social-google"><a href="#"><i class="fa fa-google-plus"></i></a></li>
								<li class="social-vimeo"><a href="#"><i class="fa fa-vimeo-square"></i></a></li>
								<li class="social-dribble"><a href="#"><i class="fa fa-dribbble"></i></a></li>
						</ul>
					</div>
					</div>
				</div>
			</div>	
		</div>
		<div class="sub-footer">
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-md-6 col-lg-6">
					<div class="wow fadeInLeft" data-wow-delay="0.1s">
					<div class="text-left">
					<p>&copy;Copyright 2015 - Medicio. All rights reserved.</p>
					</div>
					</div>
				</div>
				<div class="col-sm-6 col-md-6 col-lg-6">
					<div class="wow fadeInRight" data-wow-delay="0.1s">
					<div class="text-right">
						<p><a href="http://bootstraptaste.com/">Bootstrap Themes</a> by BootstrapTaste</p>
					</div>
                    <!-- 
                        All links in the footer should remain intact. 
                        Licenseing information is available at: http://bootstraptaste.com/license/
                        You can buy this theme without footer links online at: http://bootstraptaste.com/buy/?theme=Medicio
                    -->
					</div>
				</div>
			</div>	
		</div>
		</div>
</footer>

src/templates/snippets/form-snippet.html
<div class="row">
        <div class="col-md-12">
            <div class="callaction bg-gray">
            <div class="row">
                <h1>{{ title }}</h1>
            </div> 
            <div class="row">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-skin  btn-lg">Save</button>
                    {% if title != "Make Changes:" %}
                        <a href="{{ return_url }}" class="btn btn-danger btn-lg">Cancel</a>
                    {% else %}
                        <a href="{{ return_url }}" class="btn btn-danger btn-lg">Back</a>
                    {% endif %}
                </form>
            </div>
            {% if form.errors.non_field_errors %}
            <div class="row">
                <p class="text-danger"> 
                    {{ form.errors.non_field_errors }}
                </p>
            </div>
            {% endif %}
            </div>
        </div>
</div>

src/templates/snippets/js.html
{% load staticfiles %}
<script src="{% static "js/jquery.min.js" %}"></script>	 
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/jquery.easing.min.js" %}"></script>
<script src="{% static "js/wow.min.js" %}"></script>
<script src="{% static "js/jquery.scrollTo.js" %}"></script>
<script src="{% static "js/jquery.appear.js" %}"></script>
<script src="{% static "js/stellar.js" %}"></script>
<script src="{% static "plugins/cubeportfolio/js/jquery.cubeportfolio.min.js" %}"></script>
<script src="{% static "js/owl.carousel.min.js" %}"></script>
<script src="{% static "js/nivo-lightbox.min.js" %}"></script>
<script src="{% static "js/custom.js" %}"></script>

src/templates/snippets/nav.html
    {% load staticfiles %}
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
            <div class="container navigation">
            
                <div class="navbar-header page-scroll">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                        <i class="fa fa-bars"></i>
                    </button>
                    <a class="navbar-brand" href="{% url 'home' %}">
                        <img src="{% static "img/logo.png" %}" alt="" width="150" height="40" />
                    </a>
                </div>
                <!-- {% if request.path != login %} -->
                <!-- <div class="navbar-header page-scroll">
                    <form class="form" method="GET" action="{% url 'search' %}" style="margin-top: 25px">
                        <input type="text" name="username" placeholder="Search user..." value="{{ request.GET.query }}">
                        <button class"btn btn-default" type="submit">Search</button>
                    </form>
                </div> -->
                <!-- {% endif %} -->
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    {% url 'home' as home %}
                    {% url 'restaurants:list' as restaurant_list %}
                    {% url 'menus:list' as menu_list %}
                    {% url 'login' as login %}
                    {% if request.path != login %}
                    <li>
                        <form class="form" method="GET" action="{% url 'search' %}" style="margin-top: 10px">
                                <input type="text" name="username" placeholder="Search user..." value="{{ request.GET.query }}">
                                <button type="submit">Search</button>
                        </form>
                    </li>
                    <li class="{% if request.path  == home %}active{% endif %}"><a href="{% url 'home' %}">Home</a></li>
                    <li class="{% if request.path  == restaurant_list %}active{% endif %}"><a href="{% url 'restaurants:list' %}">Restaurants</a></li>
                    <li class="{% if request.path  == menu_list %}active{% endif %}"><a href="{% url 'menus:list' %}">Items</a></li>
                    <li class=""><a href="{% url 'logout' %}">Logout</a></li>
                    {% endif %}
                    <!-- <li><a href="#service">Service</a></li>
                    <li><a href="#doctor">Doctors</a></li>
                    <li><a href="#facilities">Facilities</a></li>
                    <li><a href="#pricing">Pricing</a></li>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="badge custom-badge red pull-right">Extra</span>More <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="index.html">Home form</a></li>
                        <li><a href="index-video.html">Home video</a></li>
                        <li><a href="index-cta.html">Home CTA</a></li>
                        <li><a href="https://bootstrapmade.com">Download</a></li>
                    </ul>
                    </li> -->
                </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
    </nav>
	